name: Process Hansard Debates

on:
  schedule:
    - cron: '*/30 18-23,0-1 * * 1-5'  # Run every 30 minutes between 1800-0200 on weekdays
    - cron: '*/30 12-15 * * 1-5' # Run every 30 minutes between 1200-1500 on weekdays
  workflow_dispatch:        # Allow manual triggers

jobs:
  process:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Process debates
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node src/index.js 